### ISSUE TITLE
Script Kiddie Moment

### ISSUE THREAD

**Issue by K74K3N** [TheMemeSniper/ANTIBODYLauncher#1]
This is sad.

**Comment by TheMemeSniper** [comment]
i know

**Comment by FancyBoiL1** [comment]
Don't talk to K74K3N or his real account he is a salty black-hat who has no life. He hates humans xd

**Comment by K74K3N** [comment]
> Don't talk to K74K3N or his real account he is a salty black-hat who has no life

Bitch.

**Comment by FancyBoiL1** [comment]
You 1000% deserved that.

**Comment by TheMemeSniper** [comment]
nobody in this issue is in the right

**Comment by Zkrail-International** [comment]
I cannot believe, that you, argued without me! ME! 

PS @K74K3N answer my calls pls.

**Comment by TheMemeSniper** [comment]
🐟
